#!/usr/bin/env python3
"""Visualize a saved SNN Pareto front solution.

Loads a *_front.csv (with weight columns) and its companion *_meta.json,
reconstructs the W1/W2 weight matrices, and generates diagnostic plots to
verify whether the training solutions make sense.

Usage:
    python analyze_network.py <front_csv>                  # most accurate solution
    python analyze_network.py <front_csv> --select sparse  # most sparse solution
    python analyze_network.py <front_csv> --select 5       # solution at index 5
    python analyze_network.py <front_csv> --select all     # one figure per solution
    python analyze_network.py <front_csv> --save           # save PNG instead of showing
    python analyze_network.py <front_csv> --select accurate --save
"""

import sys
import argparse
import json
import re
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import Normalize
import matplotlib.cm as cm


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_meta(csv_path: Path) -> dict:
    """Load the companion _meta.json.  Falls back to inferring from filename."""
    meta_path = Path(str(csv_path).replace("_front.csv", "_meta.json"))
    if meta_path.exists():
        with open(meta_path) as f:
            return json.load(f)

    # Try to infer nHidden and dataNo from filename pattern ALGO_dsX_nhY_runZ
    m = re.search(r"_ds(\d+)_nh(\d+)_run", csv_path.name)
    if m:
        ds_features = {1: 14, 2: 18, 3: 24, 4: 60}
        dataNo  = int(m.group(1))
        nHidden = int(m.group(2))
        nFeatures = ds_features.get(dataNo, 0)
        nOutputs  = 2  # all bundled datasets are binary
        D = (nFeatures + 1) * nHidden + nHidden * nOutputs
        print(f"[warn] No _meta.json found; inferred topology from filename "
              f"(nFeatures={nFeatures}, nHidden={nHidden}, nOutputs={nOutputs})")
        return {"nFeatures": nFeatures, "nHidden": nHidden, "nOutputs": nOutputs,
                "wScale": 1.0, "dataNo": dataNo, "D": D}

    raise FileNotFoundError(
        f"No _meta.json found next to {csv_path} and cannot infer topology from filename.\n"
        "Re-run the optimizer with the updated binary to generate _meta.json."
    )


def load_front(csv_path: Path, meta: dict):
    """Return (objectives, weights) arrays from the front CSV."""
    data = np.genfromtxt(csv_path, delimiter=",", skip_header=1)
    if data.ndim == 1:
        data = data.reshape(1, -1)

    objs    = data[:, :2]           # (N, 2) — f1, f2
    weights = data[:, 2:]           # (N, D)

    D_expected = meta["D"]
    if weights.shape[1] != D_expected:
        raise ValueError(
            f"Expected D={D_expected} weight columns but found {weights.shape[1]}. "
            "The CSV may have been generated by an older binary that did not save weights."
        )
    return objs, weights


# ---------------------------------------------------------------------------
# Weight matrix reconstruction
# ---------------------------------------------------------------------------

def reconstruct_matrices(w: np.ndarray, meta: dict):
    """Reshape flat weight vector into W1 (nHidden x nFeatures+1) and W2 (nOutputs x nHidden+1)."""
    nF  = meta["nFeatures"]
    nH  = meta["nHidden"]
    nO  = meta["nOutputs"]
    L1  = (nF + 1) * nH

    # Layer 1: hidden h receives weights from features + bias_h
    W1 = w[:L1].reshape(nH, nF + 1)

    # Layer 2: output o receives weights from hiddens + bias_o
    W2 = w[L1:].reshape(nO, nH)

    return W1, W2


# ---------------------------------------------------------------------------
# Solution selection
# ---------------------------------------------------------------------------

def select_solution(objs: np.ndarray, spec: str) -> int:
    if spec == "accurate":
        return int(np.argmin(objs[:, 1]))   # min f2 (training error)
    if spec == "sparse":
        return int(np.argmin(objs[:, 0]))   # min f1 (complexity)
    if spec == "balanced":
        # closest to (0,0) in objective space
        return int(np.argmin(np.linalg.norm(objs, axis=1)))
    try:
        idx = int(spec)
        if not (0 <= idx < len(objs)):
            raise ValueError(f"Index {idx} out of range [0, {len(objs)-1}]")
        return idx
    except ValueError:
        raise ValueError(f"Unknown --select value: {spec!r}. "
                         "Use 'accurate', 'sparse', 'balanced', 'all', or an integer index.")


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

DS_NAMES = {1: "Australian", 2: "Climate", 3: "German", 4: "Sonar"}


def plot_solution(objs: np.ndarray, weights: np.ndarray, meta: dict,
                  idx: int, out_path: Path | None = None):
    W1, W2 = reconstruct_matrices(weights[idx], meta)
    nF  = meta["nFeatures"]
    nH  = meta["nHidden"]
    nO  = meta["nOutputs"]
    f1, f2 = objs[idx]
    acc = 1.0 - f2
    ds_name = DS_NAMES.get(meta["dataNo"], f"ds{meta['dataNo']}")

    active_W1 = (W1 > 0).sum()
    active_W2 = (W2 > 0).sum()
    total_syn = W1.size + W2.size

    fig = plt.figure(figsize=(18, 12), layout="constrained")
    fig.suptitle(
        f"SNN solution #{idx}  |  dataset={ds_name}  |  nHidden={nH}  |  "
        f"accuracy={acc:.1%}  |  sparsity={1-f1:.1%} ({total_syn - active_W1 - active_W2} zero synapses)",
        fontsize=12,
    )

    gs = gridspec.GridSpec(2, 4, figure=fig)

    # ── 1. Pareto front ──────────────────────────────────────────────────────
    ax0 = fig.add_subplot(gs[0, 0])
    ax0.scatter(objs[:, 0], objs[:, 1], s=20, alpha=0.5, color="steelblue", label="Pareto solutions")
    ax0.scatter([f1], [f2], s=80, color="red", zorder=5, label=f"selected (#{idx})")
    ax0.set_xlabel("f1: complexity (active frac)", fontsize=8)
    ax0.set_ylabel("f2: train error", fontsize=8)
    ax0.set_title("Pareto front", fontsize=9)
    ax0.legend(fontsize=7)
    ax0.grid(True, linestyle="--", alpha=0.4)

    # ── 2. W1 heatmap (magnitudes) ────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 1:3])
    xlabel_W1 = [f"f{i}" for i in range(nF)] + ["bias"]
    im1 = ax1.imshow(W1, aspect="auto", cmap="viridis", interpolation="nearest")
    ax1.set_title(f"W1: input→hidden  ({nH}×{nF+1})  active={active_W1}/{W1.size}", fontsize=9)
    ax1.set_xlabel("Input neuron (feature / bias)", fontsize=8)
    ax1.set_ylabel("Hidden neuron", fontsize=8)
    fig.colorbar(im1, ax=ax1, shrink=0.8, label="weight")

    # ── 3. W2 heatmap (magnitudes) ────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 3])
    im2 = ax2.imshow(W2, aspect="auto", cmap="viridis", interpolation="nearest")
    ax2.set_title(f"W2: hidden→output  ({nO}×{nH})  active={active_W2}/{W2.size}", fontsize=9)
    ax2.set_xlabel("Hidden neuron (/ bias)", fontsize=8)
    ax2.set_ylabel("Output class", fontsize=8)
    ax2.set_yticks(range(nO))
    ax2.set_yticklabels([f"class {o}" for o in range(nO)], fontsize=7)
    fig.colorbar(im2, ax=ax2, shrink=0.8, label="weight")

    # ── 4. W1 sparsity mask ──────────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[1, 1:3])
    ax3.imshow(W1 > 0, aspect="auto", cmap="Greys", interpolation="nearest", vmin=0, vmax=1)
    ax3.set_title(f"W1 sparsity mask  (white=active, {active_W1/W1.size:.1%} active)", fontsize=9)
    ax3.set_xlabel("Input neuron (feature / bias)", fontsize=8)
    ax3.set_ylabel("Hidden neuron", fontsize=8)

    # ── 5. W2 sparsity mask ──────────────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 3])
    ax4.imshow(W2 > 0, aspect="auto", cmap="Greys", interpolation="nearest", vmin=0, vmax=1)
    ax4.set_title(f"W2 sparsity mask  ({active_W2/W2.size:.1%} active)", fontsize=9)
    ax4.set_xlabel("Hidden neuron (/ bias)", fontsize=8)
    ax4.set_ylabel("Output class", fontsize=8)
    ax4.set_yticks(range(nO))
    ax4.set_yticklabels([f"class {o}" for o in range(nO)], fontsize=7)

    # ── 6. Statistics panel ──────────────────────────────────────────────────
    ax5 = fig.add_subplot(gs[1, 0])
    ax5.axis("off")

    # Per-hidden-neuron: how many inputs it receives (in-degree W1)
    in_deg_hidden = (W1 > 0).sum(axis=1)   # shape (nH,)
    out_deg_hidden = (W2 > 0).sum(axis=0)        # shape (nH,)

    stats_text = (
        f"Dataset:    {ds_name}\n"
        f"nFeatures:  {nF}\n"
        f"nHidden:    {nH}\n"
        f"nOutputs:   {nO}\n"
        f"D (total):  {meta['D']}\n"
        f"wScale:     {meta['wScale']}\n"
        "\n"
        f"Train acc:  {acc:.4f}\n"
        f"Complexity: {f1:.4f}\n"
        "\n"
        f"W1 density: {active_W1/W1.size:.1%}\n"
        f"W2 density: {active_W2/W2.size:.1%}\n"
        f"Overall:    {(active_W1+active_W2)/total_syn:.1%}\n"
        "\n"
        f"Hidden in-deg (W1):\n"
        f"  mean={in_deg_hidden.mean():.1f}  max={in_deg_hidden.max()}\n"
        f"  dead={( in_deg_hidden==0).sum()} neurons\n"
        f"Hidden out-deg (W2):\n"
        f"  mean={out_deg_hidden.mean():.1f}  max={out_deg_hidden.max()}\n"
        f"  dead={(out_deg_hidden==0).sum()} neurons\n"
    )
    ax5.text(0.05, 0.97, stats_text, transform=ax5.transAxes,
             fontsize=8, verticalalignment="top", fontfamily="monospace",
             bbox=dict(boxstyle="round", facecolor="lightyellow", alpha=0.6))
    ax5.set_title("Summary", fontsize=9)

    if out_path:
        fig.savefig(out_path, dpi=150, bbox_inches="tight")
        print(f"Saved to {out_path}")
        plt.close(fig)
    else:
        plt.show()

    graph_out = None
    if out_path is not None:
        graph_out = out_path.parent / out_path.name.replace("_sol", "_graph_sol")
    plot_network_graph(W1, W2, meta, graph_out)


# ---------------------------------------------------------------------------
# Network connectivity graph
# ---------------------------------------------------------------------------

def _neuron_status(W1: np.ndarray, W2: np.ndarray, nH: int):
    """Classify each hidden neuron: 0=live, 1=dead, 2=sink (no output), 3=source (no input)."""
    has_in  = (W1 > 0).any(axis=1)              # (nH,)
    has_out = (W2 > 0).any(axis=0)               # (nH,)
    status = np.where(has_in & has_out,   0,
              np.where(~has_in & ~has_out, 1,
              np.where(has_in & ~has_out,  2,
              3)))
    return status, has_in, has_out


def plot_network_graph(W1: np.ndarray, W2: np.ndarray, meta: dict,
                       out_path: "Path | None" = None):
    """Draw a layered network graph showing only non-zero connections.

    For small networks (nHidden ≤ 60, nFeatures ≤ 40): full node-and-edge diagram.
    For large networks: condensed connectivity summary (status bar, degree
    histograms, reachability matrix).
    """
    nF   = meta["nFeatures"]
    nH   = meta["nHidden"]
    nO   = meta["nOutputs"]
    n_in = nF + 1

    status, _, _ = _neuron_status(W1, W2, nH)
    counts = {s: int((status == s).sum()) for s in range(4)}
    s_labels = {0: "live", 1: "dead", 2: "sink (no output)", 3: "source (no input)"}
    s_colors = {0: "limegreen", 1: "red", 2: "orange", 3: "gold"}

    small = nH <= 60 and nF <= 40

    if small:
        fig_h = max(7, 0.18 * max(nH, n_in))
        fig, ax = plt.subplots(figsize=(11, fig_h), layout="constrained")
        ax.set_xlim(0, 1.15)
        ax.set_ylim(-0.06, 1.06)
        ax.axis("off")

        y_in  = np.linspace(1.0, 0.0, n_in)
        y_h   = np.linspace(1.0, 0.0, nH)
        y_out = np.array([0.5]) if nO == 1 else np.linspace(0.75, 0.25, nO)

        for h in range(nH):
            for i in range(n_in):
                if W1[h, i] > 0:
                    ax.plot([0.15, 0.50], [y_in[i], y_h[h]],
                            color="black", lw=0.4, zorder=1)

        for o in range(nO):
            for h in range(nH):
                if W2[o, h] > 0:
                    ax.plot([0.50, 0.85], [y_h[h], y_out[o]],
                            color="black", lw=0.4, zorder=1)

        node_colors_h = [s_colors[s] for s in status]
        ax.scatter([0.15] * n_in, y_in,  s=40,  c="cornflowerblue",
                   zorder=5, edgecolors="navy", linewidths=0.6)
        ax.scatter([0.50] * nH,   y_h,   s=18,  c=node_colors_h, zorder=5)
        ax.scatter([0.85] * nO,   y_out, s=120, c="tomato", zorder=5,
                   marker="*", edgecolors="darkred", linewidths=0.5)

        for i, yi in enumerate(y_in):
            lbl = f"f{i}" if i < nF else "bias"
            ax.text(0.13, yi, lbl, fontsize=6, ha="right", va="center")
        for o, yo in enumerate(y_out):
            ax.text(0.87, yo, f"class {o}", fontsize=8, ha="left", va="center",
                    color="darkred", fontweight="bold")

        ax.text(0.15, 1.05, "Input",  ha="center", fontsize=9, fontweight="bold", color="navy")
        ax.text(0.50, 1.05, "Hidden", ha="center", fontsize=9, fontweight="bold", color="dimgray")
        ax.text(0.85, 1.05, "Output", ha="center", fontsize=9, fontweight="bold", color="darkred")

        from matplotlib.lines import Line2D
        legend_elements = [
            Line2D([0], [0], marker="o", color="w", markerfacecolor=s_colors[s],
                   markersize=8, label=f"{s_labels[s]} ({counts[s]})")
            for s in range(4)
        ]
        ax.legend(handles=legend_elements, loc="lower center", fontsize=7,
                  bbox_to_anchor=(0.5, -0.05), ncol=4)

        fig.suptitle(
            f"Network topology  |  live={counts[0]}  dead={counts[1]}  "
            f"sink={counts[2]}  source={counts[3]}  (of {nH} hidden neurons)",
            fontsize=10,
        )

    else:
        # Condensed view for large networks
        fig = plt.figure(figsize=(14, 8), layout="constrained")
        gs2 = gridspec.GridSpec(2, 2, figure=fig)

        # 1. Stacked bar of neuron status
        ax1 = fig.add_subplot(gs2[0, 0])
        left = 0
        for s in range(4):
            ax1.barh(0, counts[s], left=left,
                     color=s_colors[s], label=f"{s_labels[s]} ({counts[s]})")
            left += counts[s]
        ax1.set_xlim(0, nH)
        ax1.set_yticks([])
        ax1.set_xlabel("Hidden neurons", fontsize=8)
        ax1.set_title("Neuron connectivity status", fontsize=9)
        ax1.legend(fontsize=7, loc="upper right")

        # 2. In-degree histogram (W1: active inputs per hidden neuron)
        in_deg = (W1 > 0).sum(axis=1)
        ax2 = fig.add_subplot(gs2[1, 0])
        ax2.hist(in_deg, bins=min(40, n_in + 1), color="steelblue",
                 edgecolor="white", linewidth=0.3)
        ax2.axvline(in_deg.mean(), color="red", lw=1.2, linestyle="--",
                    label=f"mean={in_deg.mean():.1f}")
        ax2.set_xlabel("Active inputs per hidden neuron", fontsize=8)
        ax2.set_ylabel("Count", fontsize=8)
        ax2.set_title(f"W1 in-degree  (max={n_in})", fontsize=9)
        ax2.legend(fontsize=7)

        # 3. Out-degree histogram (W2: active outputs per hidden neuron)
        out_deg = (W2 > 0).sum(axis=0)
        ax3 = fig.add_subplot(gs2[1, 1])
        ax3.hist(out_deg, bins=min(20, nO + 2), color="darkorange",
                 edgecolor="white", linewidth=0.3)
        ax3.axvline(out_deg.mean(), color="red", lw=1.2, linestyle="--",
                    label=f"mean={out_deg.mean():.2f}")
        ax3.set_xlabel("Active outputs per hidden neuron", fontsize=8)
        ax3.set_ylabel("Count", fontsize=8)
        ax3.set_title(f"W2 out-degree  (max={nO})", fontsize=9)
        ax3.legend(fontsize=7)

        # 4. Reachability matrix: reach[o, i] = # hidden neurons h with W1[h,i]>0 AND W2[o,h]>0
        W1_act = (W1 > 0).astype(float)           # (nH, nF+1)
        W2_act = (W2 > 0).astype(float)            # (nO, nH)
        reach  = W2_act @ W1_act                   # (nO, nF+1)

        ax4 = fig.add_subplot(gs2[0, 1])
        im = ax4.imshow(reach, aspect="auto", cmap="YlOrRd",
                        interpolation="nearest", vmin=0)
        ax4.set_xlabel("Input feature (last col = bias)", fontsize=8)
        ax4.set_ylabel("Output class", fontsize=8)
        ax4.set_yticks(range(nO))
        ax4.set_yticklabels([f"class {o}" for o in range(nO)], fontsize=7)
        ax4.set_title("Reachability: input → hidden → output", fontsize=9)
        fig.colorbar(im, ax=ax4, shrink=0.8, label="# hidden neurons on path")

        # Mark features with zero paths with a cross
        for o in range(nO):
            for i in range(min(n_in, 60)):
                if reach[o, i] == 0:
                    ax4.text(i, o, "✕", ha="center", va="center",
                             fontsize=6, color="blue", fontweight="bold")

        live_pct = 100 * counts[0] / nH
        dead_pct = 100 * counts[1] / nH
        fig.suptitle(
            f"Network connectivity  |  nHidden={nH}  |  "
            f"live={live_pct:.0f}%  dead={dead_pct:.0f}%",
            fontsize=11,
        )

    if out_path is not None:
        fig.savefig(out_path, dpi=150, bbox_inches="tight")
        print(f"Graph saved to {out_path}")
        plt.close(fig)
    else:
        plt.show()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Visualize SNN Pareto front solutions",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("front_csv", help="Path to *_front.csv with weight columns")
    parser.add_argument(
        "--select", default="accurate",
        help="Which solution to visualize: 'accurate' (default), 'sparse', "
             "'balanced', 'all', or an integer index",
    )
    parser.add_argument("--save", action="store_true",
                        help="Save PNG instead of displaying interactively")
    args = parser.parse_args()

    csv_path = Path(args.front_csv)
    if not csv_path.exists():
        print(f"Error: file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    meta    = load_meta(csv_path)
    objs, weights = load_front(csv_path, meta)

    print(f"Loaded {len(objs)} Pareto solutions  (D={meta['D']} weights each)")
    print(f"Accuracy range:  [{1-objs[:,1].max():.3f}, {1-objs[:,1].min():.3f}]")
    print(f"Sparsity range:  [{1-objs[:,0].max():.3f}, {1-objs[:,0].min():.3f}]")

    if args.select == "all":
        for idx in range(len(objs)):
            out = csv_path.parent / f"{csv_path.stem}_sol{idx}.png" if args.save else None
            plot_solution(objs, weights, meta, idx, out)
        return

    idx = select_solution(objs, args.select)
    f1, f2 = objs[idx]
    print(f"Selected solution #{idx}: accuracy={1-f2:.4f}, active_frac={f1:.4f}")

    out = None
    if args.save:
        out = csv_path.parent / f"{csv_path.stem}_sol{idx}.png"

    plot_solution(objs, weights, meta, idx, out)


if __name__ == "__main__":
    main()
