#!/usr/bin/env python3
"""
extract_best_params.py

Reads Optuna SQLite DBs from a BO results directory and generates a bash
params_table.sh with a get_params(algo, ds, nh) function that returns
the optimal hyperparameter CLI flags for that combination.

Usage:
    python extract_best_params.py <bo_results_dir> [--out params_table.sh]

Then in run_experiments.sh:
    PARAMS_TABLE=./params_table.sh bash run_experiments.sh
"""

import argparse
import re
import sys
from pathlib import Path


def parse_study_name(name: str):
    """Parse 'snn_bo_<ALGO>_ds<DS>_nh<NH>' → (algo, ds, nh) or None."""
    m = re.match(r"snn_bo_(\w+)_ds(\d+)_nh(\d+)$", name)
    return (m.group(1), m.group(2), m.group(3)) if m else None


def params_to_flags(params: dict) -> str:
    """Convert Optuna best_trial.params dict to platemo_cpp CLI flags string."""
    s_lower = params["sLower"]
    s_gap   = params["sGap"]
    s_upper = min(s_lower + s_gap, 1.0)

    enc       = params["encoding_duration"]
    extra     = params["extra_eval"]
    eval_dur  = enc + extra

    parts = [
        f"--disC {params['disC']}",
        f"--disM {params['disM']}",
        f"--proM {params['proM']}",
        f"--disSM {params['disSM']}",
        f"--proSM {params['proSM']}",
        f"--sLower {s_lower}",
        f"--sUpper {s_upper:.4f}",
        f"--wscale {params['wScale']}",
        f"--dt {params['dt']}",
        f"--encoding-duration {enc}",
        f"--eval-duration {eval_dur:.2f}",
        f"--max-rate {params['max_rate']}",
        f"--refractory-period {params['refractory_period']}",
    ]
    return " ".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Generate params_table.sh from Optuna BO study databases"
    )
    parser.add_argument("bo_dir", help="Directory containing *.db Optuna study files")
    parser.add_argument("--out", default="params_table.sh",
                        help="Output bash file (default: params_table.sh)")
    args = parser.parse_args()

    bo_dir = Path(args.bo_dir)
    if not bo_dir.is_dir():
        print(f"ERROR: '{bo_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)

    dbs = sorted(bo_dir.glob("*.db"))
    if not dbs:
        print(f"ERROR: no .db files found in {bo_dir}", file=sys.stderr)
        sys.exit(1)

    try:
        import optuna
    except ImportError:
        print("ERROR: optuna not installed — pip install optuna", file=sys.stderr)
        sys.exit(1)

    optuna.logging.set_verbosity(optuna.logging.WARNING)

    entries = {}
    failed  = []

    for db in dbs:
        study_name = db.stem
        parsed = parse_study_name(study_name)
        if not parsed:
            print(f"  SKIP (unrecognised name): {study_name}", file=sys.stderr)
            continue

        algo, ds, nh = parsed
        try:
            study = optuna.load_study(
                study_name=study_name,
                storage=f"sqlite:///{db}",
            )
            bt    = study.best_trial
            flags = params_to_flags(bt.params)
            entries[(algo, ds, nh)] = (flags, bt.value)
            print(f"  OK   {study_name:<40s}  HV={bt.value:.6f}")
        except Exception as exc:
            print(f"  FAIL {study_name}: {exc}", file=sys.stderr)
            failed.append(study_name)

    if not entries:
        print("ERROR: no studies could be loaded", file=sys.stderr)
        sys.exit(1)

    # Generate params_table.sh
    out_path = Path(args.out)
    lines = [
        "# params_table.sh — auto-generated by extract_best_params.py — do not edit by hand",
        f"# Source directory : {bo_dir.resolve()}",
        f"# Studies loaded   : {len(entries)}   failed: {len(failed)}",
        "#",
        "# Usage (standalone):",
        "#   source params_table.sh",
        "#   flags=$(get_params SNSGAII 1 10)",
        "#",
        "# Usage (with run_experiments.sh):",
        "#   PARAMS_TABLE=./params_table.sh bash run_experiments.sh",
        "",
        "get_params() {",
        '    case "${1}_${2}_${3}" in',
    ]

    for (algo, ds, nh), (flags, hv) in sorted(entries.items()):
        key = f"{algo}_{ds}_{nh}"
        lines.append(f"        {key})  # HV={hv:.6f}")
        lines.append(f'            echo "{flags}" ;;')

    lines += [
        "        *)  echo '' ;;",
        "    esac",
        "}",
        "",
    ]

    out_path.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {len(entries)} entries → {out_path}")
    if failed:
        print(f"WARNING: {len(failed)} studies failed: {', '.join(failed)}")


if __name__ == "__main__":
    main()
